### ISSUE TITLE
Missing types from the `Microsoft.PowerShell.Cmdletization` namespace

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellStandard#11]
The namespace `Cmdletization` appears to be omitted.  I tested with 5.1.0-preview-02.  I'm specifically looking for `CmdletAdapter<>`, `MethodInvocationInfo`, and `QueryBuilder` but there's a few other public types there as well.

**Comment by JamesWTruher** [comment]
@joeyaiello

**Comment by SeeminglyScience** [comment]
The public API's in that namespace aren't really CIM specific afaict, even if that is the only thing they are used for at the moment.  I'm using them for a separate API that is cross platform.

My assumption was that inheriting `CmdletAdapter` and generating my own cdxml was within the realm of support as none of the required members are internal and the namespace isn't marked as such.

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience the @PowerShell/powershell-committee had deliberately left out the cmdletization apis as they are currently only used by WMIv2 providers.  Can you say more about the adapter your building?  If there's life for cdxml beyond WMI, I'd be more than happy to support that.

**Comment by SeeminglyScience** [comment]
I'm in the process of rewriting [EditorServicesCommandSuite](https://github.com/SeeminglyScience/EditorServicesCommandSuite) in C# to make it easier to use and easier to consume from other services.  Because of that it didn't make sense to me to require the overhead of a cmdlet if it could be called outside of a runspace.

However, I wanted to keep the ability to invoke them directly and the cmdletization API's provide a pretty easy way of automatically generating functions for each new refactor option.  In my build script  I can load my library, scan it with reflection for new API's, and generate a new cdxml module.  Every option that can be configured with a settings file can instead be configured via parameters.

I could of course generate my own ps1 files, but I can't implement `StopProcessing` without it.  The `StoppingEvent` on `PSScriptCmdlet` is only accessible through implementing `StopProcessing` on `CmdletAdapter`.  It's also a great deal easier to just generate the XML.

That's what I'm using them for, but I think there's a lot of use cases.  It can be a pretty easy way to provide cmdlets for an existing API, depending on how that API is set up.  Looking at the cmdletization API's, it does seem like they were designed to be implemented externally, just the documentation to do so was never put together.

**Comment by SteveL-MSFT** [comment]
Thanks for the details, I'll try to remember to bring this up at the next @PowerShell/powershell-committee meeting (tomorrow0

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree that the apis would be useful.  @JamesWTruher will investigate the cost of adding this to the PS Std 5.1 release so no commitment this will make it to GA at this time

**Comment by SeeminglyScience** [comment]
Thank you @SteveL-MSFT! I'll continue to build separate FullCLR/CoreCLR assemblies in the mean time.

Side note, the members of powershell-committee team are private (link goes to 404 message).  Mentioning only in case that wasn't intended.

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience the @PowerShell/powershell-committee team is set to `visible` with the only other option being `secret`.  Don't see any other options that affect visibility.  The members of that team are exactly the same as https://github.com/PowerShell/PowerShell/blob/master/docs/community/governance.md#current-committee-members

**Comment by SeeminglyScience** [comment]
I've confirmed preview 4 has everything I need here.  Really appreciate the quick turn around @JamesWTruher, thank you!
