### ISSUE TITLE
Assemblies Other Than SMA.dll

### ISSUE THREAD

**Issue by lordmilko** [PowerShell/PowerShellStandard#13]
Will other assemblies found in the [PowerShell 5 SDK](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/) eventually be included in the PowerShell Standard package?

Specifically, I'm interested to know whether Microsoft.PowerShell.Commands.Utility.dll will ever be included, or whether plan is to stick to System.Management.Automation.dll only

**Comment by JamesWTruher** [comment]
The current plan is that it's only SMA to be part of the PowerShell Standard. The target for PowerShell Standard is for module authors rather than hosting scenarios.

**Comment by lordmilko** [comment]
Thanks James
