### ISSUE TITLE
ProvideInfo is missing from CmdletProvider in 5.1 PS Standard

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellStandard#14]
![image](https://user-images.githubusercontent.com/1256531/38703496-00811eec-3e69-11e8-8b57-48c2cc68c8c8.png)

PowerShell Standard 5

```
<PackageReference Include="PowerShellStandard.Library" Version="5.1.0-preview-03" />
```

```
namespace System.Management.Automation.Provider
{
    public abstract class CmdletProvider
```

![image](https://user-images.githubusercontent.com/1256531/38703169-2029a396-3e68-11e8-988c-b9e407ea1b6d.png)

![image](https://user-images.githubusercontent.com/1256531/38703203-30a87cc4-3e68-11e8-9507-9a2a707c530b.png)

PowerShell Standard 3

```
<PackageReference Include="PowerShellStandard.Library" Version="3.0.0-preview-02" />
```

```
namespace System.Management.Automation.Provider
{
    public abstract class CmdletProvider : IResourceSupplier
```

![image](https://user-images.githubusercontent.com/1256531/38703285-7b9e475e-3e68-11e8-8bba-126623cb40d6.png)

**Comment by JamesWTruher** [comment]
this is a syntax error right? Don't you actually need to provide a providerinfo here rather than the type?
I've fixed the visibility, though.

**Comment by Jaykul** [comment]
It's not a syntax error, you've hidden too much from the CmdletProvider.  It's should have additional properties:

```
PSDriveInfo PSDriveInfo
PSTransactionContext CurrentPSTransaction
```

maybe even

```
ProviderInfo ProviderInfo
```

This prevents porting the P2F provider framework to use PowerShellStandard.Library
