### ISSUE TITLE
Where do we find the 5.1 variety?

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellStandard#2]
Hey Jim!  I can only find PowerShellStandard.Library 3.0 on NuGet:

https://www.nuget.org/packages/PowerShellStandard.Library

How can I find the package for 5.1+?  Thanks!

**Comment by dsolodow** [comment]
Looks like it was released a few days ago (about a week after you opened this).

**Comment by MaximoTrinidad** [comment]
@daviwil 

Here's the link: https://www.nuget.org/packages/PowerShellStandard.Library/5.1.0-preview-01

**Comment by daviwil** [comment]
Thanks all! I saw the announcement this morning.
