### ISSUE TITLE
Several properties missing from CmdletProvider

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShellStandard#26]
At _least_ the following properties are missing:

```csharp
        public PSTransactionContext CurrentPSTransaction { get; }
        protected object DynamicParameters { get; }
        protected PSDriveInfo PSDriveInfo { get; }
        protected internal ProviderInfo ProviderInfo { get; }
```

The `TransactionAvailable()` method is still there, but there's no way I can see to get at the transaction

**Comment by Jaykul** [comment]
Without these, the P2F framework won't compile against PowerShellStandard.Library, and thus, [SHiPS](https://github.com/PowerShell/SHiPS/blob/development/src/Microsoft.PowerShell.SHiPS/Microsoft.PowerShell.SHiPS.csproj#L65-L69) isn't using PowerShellStandard -- they are shipping TWO SEPARATE BINARY MODULES (one targeting a private `1.0.0-alpha9` nuget package of SMA for Windows) ...

I am honestly not sure if it's _even possible_ to write a **provider** using this library, but it certainly isn't possible to support Transactions or DynamicParameters.

**Comment by JamesWTruher** [comment]
something went seriously wrong with one of my last merges. All sorts of things are missing. I'm tracking down what happened.

**Comment by Jaykul** [comment]
This bug was associated with the PR we closed last week, @JamesWTruher -- so I think it's fixed now. 
I'll check against beta 4 tomorrow.

**Comment by JamesWTruher** [comment]
@Jaykul I will also be removing the TransactionAvailable method in preview05, your arguments were persuasive, and we can always add it back.
