### ISSUE TITLE
Issues when building modules against PowerShell.Standard.Library 5.1 Preview.1

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShellStandard#3]
Attributes that users `params` in constructors no longer work.

```[ValidateSet("pending", "submitted", "shelved")]```
must be written as 
```[ValidateSet(new[]{"pending", "submitted", "shelved"})]```

Same with `OutputType`, `Alias` etc.

`PSMemberInfoCollection<PSPropertyInfo>` no longer has an indexer with a `string` parameter.

so 
 ```
PSMemberInfoCollection<PSPropertyInfo>properties;
properties["name"];
```
will now result in ```Argument1: cannot convert from 'string' to 'int'```

**Comment by JamesWTruher** [comment]
the ValidateSet issue was somewhat general, my tools eliminated the params modifier. I'll have that fixed shortly

**Comment by JamesWTruher** [comment]
fixed in https://github.com/PowerShell/PowerShellStandard/pull/9

**Comment by powercode** [comment]
Can you publish a preview-02?

**Comment by JamesWTruher** [comment]
yep, that's the plan - should be tomorrow
