### ISSUE TITLE
SMA.Runspace.CreatePipeline() Missing in PowerShellStandard 5.1

### ISSUE THREAD

**Issue by darkonejr** [PowerShell/PowerShellStandard#4]
In the PowerShell Standard 5.1 version of the library.  SMA.Runspace.CreatePipeline() seems missing. Is this a deprecated API?

**Comment by JamesWTruher** [comment]
yes, it was pulled (it's also not in PSS3) because it's a V1 API which we would like to remove. It's used internally, but we don't want it to move forward.

**Comment by masaeedu** [comment]
@JamesWTruher What should we be using instead of `CreatePipeLine`?
