### ISSUE TITLE
PSEventUnsubscribedEventHandler delegate has incorrect event args

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShellStandard#50]
`PSEventUnsubscribedEventHandler.Invoke` has it's event arguments parametered typed as `PSEventArgs`  
 instead of `PSEventUnsubscribedEventArgs`

**Comment by tylerl0706** [comment]
Fixed in https://github.com/PowerShell/PowerShellStandard/pull/51
