### ISSUE TITLE
Missing Runspace.CreatePipeline

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellStandard#55]
Hey guys,

Realized today that this assembly is missing `Runspace.CreatePipeline`

![image](https://user-images.githubusercontent.com/1256531/50036396-e88d1380-ffc5-11e8-95e3-0160689d2aea.png)

**Comment by TylerLeonhardt** [comment]
@adamdriscoll I think this is by design: https://github.com/PowerShell/PowerShellStandard/issues/4

**Comment by adamdriscoll** [comment]
@TylerLeonhardt Should have done a search ;) Ok. Thanks!
