### ISSUE TITLE
PSObject.Properties is using int instead of string

### ISSUE THREAD

**Issue by mallochine** [PowerShell/PowerShellStandard#6]
I run into this compiler error when trying to compile "JsonObject.cs" in the github.com/Powershell/Powershell repo.

On this line:
```
151                 // Compare case insensitive to tell the user to use the -AsHashTable option instead.
152                 // This is because PSObject cannot have keys with different casing.
153                 PSPropertyInfo property = result.Properties[entry.Key]; // <---------- THIS ONE
154                 if (property != null)
```

entry.Key is a string.
The error was something like: cannot use string in result.Properties[]

I'm sorry I can't provide more detailed response as I blew away the environment in favor of a workaround.

**Comment by JamesWTruher** [comment]
@mallochine  do you recall whether this was standard 5.1 or 3?

**Comment by mallochine** [comment]
definitely 5.1. I used this:

-reference:$(TOP)/deps/Microsoft.PowerShell.5.ReferenceAssemblies.1.1.0/lib/net4/System.Management.Automation.dll

**Comment by JamesWTruher** [comment]
fixed in https://github.com/PowerShell/PowerShellStandard/pull/9

**Comment by mallochine** [comment]
awesome! Glad I was able to contribute
