### ISSUE TITLE
The 'params' keyword is left out for array type parameters

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShellStandard#7]
For `OutputTypeAttribute`, the constructor is `public OutputTypeAttribute(params Type[] type)`.
However, in `PowerShellStandard.Library`, the `params` keyword is left out, and thus I got compilation errors when compiling some existing code.

It's possible that the `params` keyword in other APIs is also left out in the ref assembly.
The `params` keyword is represented in the reflection metadata by a 'CustomAttribute':

```powershell
PS:13> $parameterInfo.CustomAttributes

AttributeType              Constructor  ConstructorArguments NamedArguments
-------------              -----------  -------------------- --------------
System.ParamArrayAttribute Void .ctor() {}                   {}
```

-------------------------------------

Other instances:
`ScriptBlock.Invoke(object[] args)`

**Comment by JamesWTruher** [comment]
yes - https://github.com/PowerShell/PowerShellStandard/issues/3 is a specific instance of this

**Comment by JamesWTruher** [comment]
fixed in https://github.com/PowerShell/PowerShellStandard/pull/9
