### ISSUE TITLE
No reference to PowerShellProcessInstance class

### ISSUE THREAD

**Issue by leonardder** [PowerShell/PowerShellStandard#75]
This module lacks support for [PowerShellProcessInstance](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.powershellprocessinstance?view=pscore-6.2.0)

**Comment by JamesWTruher** [comment]
yes, this is correct. The V1 pipeline APIs were explicitly excluded from PowerShell Standard

**Comment by leonardder** [comment]
Thanks for pointing this out. Does this mean that the use of this class is discouraged/deprecated? What would be the power shell standard way to run ps out of process?

**Comment by iSazonov** [comment]
@leonardder It is discussed in https://github.com/PowerShell/PowerShell/issues/11674
