### ISSUE TITLE
PowershellStandard 7?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellStandard#76]
Powershell Standard 7.0.0 Preview was pushed to Nuget 5 days ago, but there are no related commits here. Has this open source development been moved or abandoned? What's the deal?
https://www.nuget.org/packages/PowerShellStandard.Library/7.0.0-preview.1

@joeyaiello @rjmholt @TylerLeonhardt

**Comment by rjmholt** [comment]
@JamesWTruher @SteveL-MSFT

**Comment by JamesWTruher** [comment]
@JustinGrote just running a bit behind, it's there now. I've merged the branch that was used to release the preview.
